<div class="jumbotron">
    <h1>App <span class="zf-green">Home View</span></h1>
    <p>
        This is the dashboard for Acme <span class="zf-green">Module</span>
    </p>
</div>
<div class="row">
<div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Panel Section</h3>
            </div>
            <div class="panel-body">
                <p>
                    This panel is for more stuff.
                </p>
            </div>
        </div>
    </div>
</div>