<div class="jumbotron">
    <h3>Manage <span class="zf-green">Notifications</span></h3>
    <p>
        Create and manage notifications for different systems resources.
        Account Manager's can define conditions that when triggered will automatically send 
        an email notification.  For example when a Route Guide order has not been updated with 
        a delivered status after a set number of days from picked up.
    </p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Placeholder</h3>
            </div>
            <div class="panel-body">
                <p>
                    If you need any help or support as for Dan.
                </p>

                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank">Ping us on IRC &raquo;</a></p>
            </div>
        </div>
    </div>

</div>